.TH CLIENT 1 "2026-09-23" "libmyutils 1.0" "libmyutils Manual"
.SH NAME
client \- driver program that tests the libmyutils library
.SH SYNOPSIS
.nf
client
.fi
.SH DESCRIPTION
Runs tests for the string functions and file functions of libmyutils and prints the results. It creates a file named sample.txt in the current directory.
.SH AUTHOR
RAHAT RAZA <rahatraza487@gmail.com>
